export const PORTFOLIO_ADD = 'PORTFOLIO_ADD';
export const PORTFOLIO_REMOVE = 'PORTFOLIO_REMOVE';
export const PORTFOLIO_NOTES = 'PORTFOLIO_NOTES';
export const TRADE_ADD = 'TRADE_ADD';
export const TRADE_REMOVE = 'TRADE_REMOVE';
export const PORTFOLIOS_INITIAL = 'PORTFOLIOS_INITIAL';
